cc_library(
    name = "iwstring_data_source",
    visibility = ["//visibility:public"],
    srcs = [
        "iwmmap.cc",
        "iwstring_data_source.cc",
        "string_data_source.cc",
    ],
    hdrs = [
        "iwmmap.h",
        "iwstring_data_source.h",
        "string_data_source.h",
    ],
    deps = [
        "//Foundational/iwmisc:iwconfig",
        "//Foundational/iwaray:iwaray",
        "//Foundational/iwcrex:iwcrex",
        "//Foundational/iwstring:iwstring",
    ],
)
