cc_library(
     name = "iwstring",
     visibility = ["//visibility:public"],
     srcs = [
        "iwstring.cc",
        "IWString_class.cc",
        "iwstring_and_file_descriptor.cc",
        "iwwrite.cc",
        "iwwrite_block.cc",
        "iwstrncasecmp.cc",
        "iwstring_strstream.cc",
        "iwzlib.cc",
        "iw_stl_hash_map.cc",
        "remove_suffix.cc",
        "unhtml.cc",
     ],
     hdrs = [
         "iwhash.h",
         "iwstring.h",
         "iw_stl_hash_set.h",
         "iw_stl_hash_map.h",
         "iwzlib.h",
     ],
     deps = [
         "//Foundational/iwaray:iwaray",
         "//Foundational/iwmisc:iwconfig",
     ],
)
