cc_library(
    name = "iwcrex",
    visibility = ["//visibility:public"],
    srcs = [
        "grep-2.5.regex.c",
        "iwgrep-2.5.cc",
        "_iwgrep25regex.cc",
    ],
    hdrs = [
        "config.h",
        "grep-2.5.config.h",
        "grep-2.5.posix.regex.h",
        "grep-2.5.regex.h",
        "iwcrex.h",
        "iwgrep-2.5.h",
    ],
    deps = [
        "//Foundational/iwmisc:iwconfig",
        "//Foundational/iwaray:iwaray",
        "//Foundational/iwstring:iwstring",
    ],
)
